language: bash
services: docker

env:
  - VERSION=latest
  - VERSION=2.47
  - VERSION=2.46
  - VERSION=2.45
  - VERSION=2.44
  - VERSION=2.43
  - VERSION=2.42
  - VERSION=2.41
  - VERSION=2.40
  - VERSION=2.39

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - test latest = "$VERSION" || cd "$VERSION"
  - image="marceloalmeida/docker-jenkins-dind:${VERSION}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
